version: 0.2

phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - dotnet restore TaskApi.csproj
      - dotnet publish TaskApi.csproj --configuration Release --runtime linux-x64 --self-contained false --output ./publish
      - cd publish && zip -r ../TaskApi.zip . && cd ..
      - ls -la TaskApi.zip

artifacts:
  files:
    - TaskApi.zip
    - serverless.yml
    - buildspec-deploy.yml
    - buildspec-migration.yml
  discard-paths: no