version: 0.2

phases:
  install:
    commands:
      - dotnet tool install --global dotnet-ef
      - export PATH="$PATH:/root/.dotnet/tools"
  build:
    commands:
      - |
        echo "RUN_MIGRATION = $RUN_MIGRATION"
        if [ "$RUN_MIGRATION" = "true" ]; then
          echo "Running Migrations..." 
          dotnet restore
          dotnet ef database update --connection "$CONNECTION_STRING" --project TaskApi.csproj
          echo "Migrations complete. Set SSM back to false."
        else
          echo "Skipping migrations. SSM flag is false."
        fi