version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - echo "Restoring packages..."
      - dotnet restore TaskApi.csproj

  build:
    commands:
      - echo "Building..."
      - dotnet build TaskApi.csproj --configuration Release --no-restore

  post_build:
    commands:
      - echo "Publishing..."
      - dotnet publish TaskApi.csproj
          --configuration Release
          --runtime linux-x64
          --self-contained false
          --output ./publish

      - echo "Zipping..."
      - cd publish && zip -r ../lambda.zip . && cd ..

      - echo "Copying to fixed S3 path..."
      - aws s3 cp lambda.zip s3://demo-project-artifact-hasil/latest/lambda.zip

      # - echo "Deploying to Lambda..."
      # - aws lambda update-function-code
      #     --function-name demo-project-dev-demo-project-lambda-sls
      #     --zip-file fileb://lambda.zip
      #     --region ap-south-1

      - echo "Deploying Infrastructure..."
      - npm run deploy

artifacts:
  files:
    - lambda.zip
  discard-paths: yes