AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to deploy CodeBuild
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/6ca6975a44c5c62331901f1d00c82dc5.template
      Parameters:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: ap-south-1a
  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/6ca6975a44c5c62331901f1d00c82dc5.template
      Parameters:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: ap-south-1b
  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/6ca6975a44c5c62331901f1d00c82dc5.template
      Parameters:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.3.0/24
        AvailabilityZone: ap-south-1a
  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/6ca6975a44c5c62331901f1d00c82dc5.template
      Parameters:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.4.0/24
        AvailabilityZone: ap-south-1b
  InternetGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/f5c071f0c63534278fef65df18a5ec13.template
      Parameters:
        VpcId:
          Ref: MyVPC
  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/909933292ccda6c4804a3f21d9279582.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - PublicSubnet1
          - Outputs.SubnetId
  RoutingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/706c74d6def2029e036c875123c1dcec.template
      Parameters:
        VpcId:
          Ref: MyVPC
        InternetGateway:
          Fn::GetAtt:
          - InternetGatewayStack
          - Outputs.InternetGatewayId
        NatGateway:
          Fn::GetAtt:
          - NatGatewayStack
          - Outputs.NatGatewayId
        PublicSubnet1:
          Fn::GetAtt:
          - PublicSubnet1
          - Outputs.SubnetId
        PublicSubnet2:
          Fn::GetAtt:
          - PublicSubnet2
          - Outputs.SubnetId
        PrivateSubnet1:
          Fn::GetAtt:
          - PrivateSubnet1
          - Outputs.SubnetId
        PrivateSubnet2:
          Fn::GetAtt:
          - PrivateSubnet2
          - Outputs.SubnetId
  LambdaSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/a9911ab2b31bd11de086b17cff78ed85.template
      Parameters:
        GroupDescription: This is a SG for Lambda created by CF
        VpcId:
          Ref: MyVPC
  RDSSecurityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaSecurityGroup
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/a9911ab2b31bd11de086b17cff78ed85.template
      Parameters:
        GroupDescription: This is a SG For RDS created by CF
        VpcId:
          Ref: MyVPC
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId:
          Fn::GetAtt:
          - LambdaSecurityGroup
          - Outputs.SecurityGroupId
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/hasil-dummy-cf-templates/400acf40e5eb1875e6ac3c6a9c7cb4d3.template
      Parameters:
        DBInstanceIdentifier: dummy-database
        PrivateSubnet1:
          Fn::GetAtt:
          - PrivateSubnet1
          - Outputs.SubnetId
        PrivateSubnet2:
          Fn::GetAtt:
          - PrivateSubnet2
          - Outputs.SubnetId
        MasterUsername: dummy_admin
        MasterUserPassword: Dummy#1234
        RDSSecurityGroupId:
          Fn::GetAtt:
          - RDSSecurityGroup
          - Outputs.SecurityGroupId
  DatabaseConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: dummy-project/connection-string
      SecretString:
        Fn::Sub:
        - Host=${Endpoint};Port=5432;Database=postgres;Username=dummy_admin;Password=Dummy#1234
        - Endpoint:
            Fn::GetAtt:
            - RDSStack
            - Outputs.RDSEndpoint
  DemoSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: demo-queue2
  SNSEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: demo-project-email-topic
      Subscription:
      - Endpoint: hasiltr@gmail.com
        Protocol: email
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: taskapi-userpool
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: taskapi-client
      UserPoolId:
        Ref: CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
  CodeBuildDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            - lambda:*
            - logs:*
            - ec2:*
            - codeconnections:*
            - ssm:*
            - kms:*
            - secretsmanager:*
            - cloudformation:*
            - iam:*
            - apigateway:*
            - sqs:*
            Resource: '*'
        PolicyName: CodeBuildDeployPolicy
  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-deploy
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
        - CodeBuildDeployRole
        - Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-deployment.yml
  CodeBuildMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            - lambda:*
            - logs:*
            - ec2:*
            - rds:*
            - codeconnections:*
            - ssm:*
            - kms:*
            - secretsmanager:*
            Resource: '*'
        PolicyName: CodeBuildMigrationPolicy
  CodeBuildMigrationProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-migration
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: CONNECTION_STRING
          Value: dummy-project/connection-string
          Type: SECRETS_MANAGER
        - Name: RUN_MIGRATIONS
          Value: 'false'
      ServiceRole:
        Fn::GetAtt:
        - CodeBuildMigrationRole
        - Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-migration.yml
      VpcConfig:
        VpcId:
          Ref: MyVPC
        Subnets:
        - Fn::GetAtt:
          - PrivateSubnet1
          - Outputs.SubnetId
        - Fn::GetAtt:
          - PrivateSubnet2
          - Outputs.SubnetId
        SecurityGroupIds:
        - Fn::GetAtt:
          - LambdaSecurityGroup
          - Outputs.SecurityGroupId
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            - codeconnections:*
            - codebuild:*
            Resource: '*'
        PolicyName: CodePipelinePolicy
  ArtifactBucket:
    Type: AWS::S3::Bucket
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
        - CodePipelineRole
        - Arn
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactBucket
      Stages:
      - Actions:
        - ActionTypeId:
            Category: Source
            Owner: AWS
            Provider: CodeStarSourceConnection
            Version: '1'
          Name: GitHub
          Configuration:
            ConnectionArn: 
              arn:aws:codeconnections:ap-south-1:292578125952:connection/b317277a-0fbe-4331-827e-f33e3917a3ff
            FullRepositoryId: Hasil-21/Dummy-Files-Hasil
            BranchName: main
          OutputArtifacts:
          - Name: SourceOutput
        Name: Source
      - Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Name: API
          Configuration:
            ProjectName: demo-project-deploy
          InputArtifacts:
          - Name: SourceOutput
        Name: LambdaDeploy
      - Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Name: DB
          Configuration:
            ProjectName: demo-project-migration
          InputArtifacts:
          - Name: SourceOutput
        Name: DatabaseMigration
Outputs:
  SlsLambdaSecurityGroup:
    Value:
      Fn::GetAtt:
      - LambdaSecurityGroup
      - Outputs.SecurityGroupId
  SlsPrivateSubnet1:
    Value:
      Fn::GetAtt:
      - PrivateSubnet1
      - Outputs.SubnetId
  SlsPrivateSubnet2:
    Value:
      Fn::GetAtt:
      - PrivateSubnet2
      - Outputs.SubnetId
  SlsSQSQueueArn:
    Value:
      Fn::GetAtt:
      - DemoSQSQueue
      - Arn
  SQSUrl:
    Value:
      Ref: DemoSQSQueue
  CognitoUserPoolArn:
    Value:
      Fn::GetAtt:
      - CognitoUserPool
      - Arn
  SnsTopicEmailArn:
    Value:
      Ref: SNSEmailTopic
