service: demo-project

provider:
  name: aws
  runtime: dotnet8
  region: ap-south-1
  stage: dev
  versionFunctions: false

  vpc:
    subnetIds:
      - '{{resolve:ssm:/demo-project/dev/private-subnet-1a}}'
      - '{{resolve:ssm:/demo-project/dev/private-subnet-1b}}'
    securityGroupIds:
      - '{{resolve:ssm:/demo-project/dev/lambda-sg-id}}'

  environment:
    ASPNETCORE_ENVIRONMENT: Production
    CONNECTION_STRING: '{{resolve:ssm:/demo-project/dev/connection-string}}'
    BUCKET_NAME: '{{resolve:ssm:/demo-project/dev/s3-bucket-presigned}}'
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - ec2:*
            - ssm:*
            - secretsmanager:*
            - s3:GetObject
          Resource: "*"

package:
  artifact: TaskApi.zip

functions:
  task-api:
    handler: TaskApi
    events:
      - http:
          path: /api/tasks
          method: GET
      - http:
          path: /api/tasks/{id}
          method: GET
      - http:
          path: /api/tasks
          method: POST
      - http:
          path: /api/tasks/{id}
          method: DELETE
      - http:
          path: /api/tasks/{id}
          method: PUT
      - http:
          path: /api/assets/{filename}
          method: GET
      - http:
          path: /api/products
          method: GET
      - http:
          path: /api/products/{id}
          method: GET
      - http:
          path: /api/products
          method: POST
      - http:
          path: /api/products/{id}
          method: PUT
      - http:
          path: /api/products/{id}
          method: DELETE

    