service: demo-project

provider: 
  name: aws
  runtime: dotnet8
  region: ap-south-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
        - ec2:*
        - ssm:*
        - kms:Decrypt
        - sqs:*
        - sns:*
      Resource: "*"

functions:
  demo-project-lambda-sls:
    handler: TaskApi 
    memorySize: 512
    timeout: 30
    events: 
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer:
            name: cognito-authorizer
            type: COGNITO_USER_POOLS
            arn: ${cf:demo-project-cf.CognitoUserPoolArn}
      - http:
          path: /
          method: ANY
          cors: true
          authorizer:
            name: cognito-authorizer
            type: COGNITO_USER_POOLS
            arn: ${cf:demo-project-cf.CognitoUserPoolArn}
    vpc: 
      securityGroupIds:
        - ${cf:demo-project-cf.SlsLambdaSecurityGroup}
      subnetIds:
        - ${cf:demo-project-cf.SlsPrivateSubnet1}
        - ${cf:demo-project-cf.SlsPrivateSubnet2}
    environment:
      CONNECTION_STRING: ${ssm:/aws/reference/secretsmanager/dummy-project/connection-string}
      SQS_URL: ${cf:demo-project-cf.SQSUrl}  
    destinations:
      onSuccess: ${cf:demo-project-cf.SlsSQSQueueArn}

  demo-project-process-sqs:
    handler: TaskApi::SqsProcessor.Function::FunctionHandler
    memorySize: 256
    timeout: 30
    environment:
      SNS_TOPIC_ARN: ${cf:demo-project-cf.SnsTopicEmailArn}
    events: 
      - sqs:
          arn: ${cf:demo-project-cf.SlsSQSQueueArn}
          batchSize: 1
          functionResponseType: ReportBatchItemFailures



