service: demo-project

provider: 
  name: aws
  runtime: dotnet8
  region: ap-south-1
  versionFunctions: false

functions:
  demo-project-lambda-sls:
    handler: TaskApi 
    memorySize: 512
    timeout: 30
    events: 
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    vpc: 
      securityGroupIds:
        - sg-0fae0b4067744f26a
      subnetIds:
        - subnet-0d1cbb6674856b351
        - subnet-0ba92b13c578ff7dc
    environment:
      CONNECTION_STRING: ${ssm:/aws/reference/secretsmanager/demo-project/connection-string}
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - logs:*
              - ec2:*
              - ssm:*
              - kms:Decrypt    
            Resource: "*"



