AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to deploy CodeBuild

Resources:

  #VPC

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  #Subnet

  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/subnet.yml
      Parameters:
        VpcId: !Ref MyVPC
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: ap-south-1a

  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/subnet.yml
      Parameters:       
        VpcId: !Ref MyVPC
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: ap-south-1b

  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/subnet.yml
      Parameters:    
        VpcId: !Ref MyVPC
        CidrBlock: 10.0.3.0/24
        AvailabilityZone: ap-south-1a

  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/subnet.yml
      Parameters:
        VpcId: !Ref MyVPC
        CidrBlock: 10.0.4.0/24
        AvailabilityZone: ap-south-1b

  #Internet Gateway

  InternetGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/internet-gateway.yml
      Parameters:
        VpcId: !Ref MyVPC

  #Nat Gateway

  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/nat-gateway.yml
      Parameters:
        SubnetId: !GetAtt PublicSubnet1.Outputs.SubnetId

  #Route Table

  RoutingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/routing.yml
      Parameters:
        VpcId: !Ref MyVPC
        InternetGateway: !GetAtt InternetGatewayStack.Outputs.InternetGatewayId
        NatGateway: !GetAtt NatGatewayStack.Outputs.NatGatewayId
        PublicSubnet1: !GetAtt PublicSubnet1.Outputs.SubnetId
        PublicSubnet2: !GetAtt PublicSubnet2.Outputs.SubnetId
        PrivateSubnet1: !GetAtt PrivateSubnet1.Outputs.SubnetId
        PrivateSubnet2: !GetAtt PrivateSubnet2.Outputs.SubnetId

  #Security Group

  LambdaSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Network/security-group.yml
      Parameters:
        GroupDescription: This is a SG for Lambda created by CF
        VpcId: !Ref MyVPC

  RDSSecurityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaSecurityGroup
    Properties:
      TemplateURL: Network/security-group.yml
      Parameters:
        GroupDescription: This is a SG For RDS created by CF
        VpcId: !Ref MyVPC
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId: !GetAtt LambdaSecurityGroup.Outputs.SecurityGroupId

  #Database

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: Database/rds.yml
      Parameters:
        DBInstanceIdentifier: dummy-database
        PrivateSubnet1: !GetAtt PrivateSubnet1.Outputs.SubnetId
        PrivateSubnet2: !GetAtt PrivateSubnet2.Outputs.SubnetId
        MasterUsername: dummy_admin
        MasterUserPassword: Dummy#1234
        RDSSecurityGroupId: !GetAtt RDSSecurityGroup.Outputs.SecurityGroupId

  #Connection String Store in Secret Manager

  DatabaseConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: dummy-project/connection-string
      SecretString: !Sub
        - Host=${Endpoint};Port=5432;Database=postgres;Username=dummy_admin;Password=Dummy#1234
        - Endpoint: !GetAtt RDSStack.Outputs.RDSEndpoint

  #SQS

  DemoSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: demo-queue2

  #Cognito

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: taskapi-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: taskapi-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        
  #Deployment

  CodeBuildDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                  - lambda:*
                  - logs:*
                  - ec2:*
                  - codeconnections:*
                  - ssm:*
                  - kms:*
                  - secretsmanager:*
                  - cloudformation:*
                  - iam:*
                  - apigateway:*
                  - sqs:*
                Resource: "*"
          PolicyName: CodeBuildDeployPolicy

  CodeBuildDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-deploy
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildDeployRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-deployment.yml
      

  #Migration

  CodeBuildMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
        
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                  - lambda:*
                  - logs:*
                  - ec2:*
                  - rds:*
                  - codeconnections:*
                  - ssm:*
                  - kms:*
                  - secretsmanager:*
                Resource: "*"
          PolicyName: CodeBuildMigrationPolicy

  CodeBuildMigrationProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: demo-project-migration
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: CONNECTION_STRING
            Value: dummy-project/connection-string
            Type: SECRETS_MANAGER
      ServiceRole: !GetAtt CodeBuildMigrationRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/Hasil-21/Dummy-Files-Hasil.git
        GitCloneDepth: 1
        BuildSpec: buildspec-migration.yml
      VpcConfig:
        VpcId: !Ref MyVPC
        Subnets:
          - !GetAtt PrivateSubnet1.Outputs.SubnetId
          - !GetAtt PrivateSubnet2.Outputs.SubnetId
        SecurityGroupIds:
          - !GetAtt LambdaSecurityGroup.Outputs.SecurityGroupId

  #Pipeline

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:  
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codeconnections:*
                  - codebuild:*
                Resource: "*"
          PolicyName: CodePipelinePolicy

  ArtifactBucket:
    Type: AWS::S3::Bucket

  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Name: GitHub
              Configuration:
                ConnectionArn: arn:aws:codeconnections:ap-south-1:292578125952:connection/b317277a-0fbe-4331-827e-f33e3917a3ff
                FullRepositoryId: Hasil-21/Dummy-Files-Hasil
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput
          Name: Source 

        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Name: API
              Configuration:
                ProjectName: demo-project-deploy
              InputArtifacts:
                - Name: SourceOutput
          Name: LambdaDeploy

        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Name: DB
              Configuration:
                ProjectName: demo-project-migration
              InputArtifacts:
                - Name: SourceOutput
          Name: DatabaseMigration
  
Outputs:
  SlsLambdaSecurityGroup:
    Value: !GetAtt LambdaSecurityGroup.Outputs.SecurityGroupId
  
  SlsPrivateSubnet1:
    Value: !GetAtt PrivateSubnet1.Outputs.SubnetId

  SlsPrivateSubnet2:
    Value: !GetAtt PrivateSubnet2.Outputs.SubnetId

  SlsSQSQueueArn:
    Value: !GetAtt DemoSQSQueue.Arn

  SQSUrl:
    Value: !Ref DemoSQSQueue

  CognitoUserPoolArn:
    Value: !GetAtt CognitoUserPool.Arn



