AWSTemplateFormatVersion: 2010-09-09
Description: This is a cloudformation template for RDS database

Resources: 

  TaskRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This is a RDS subnet group for Private subnets
      SubnetIds:
        - '{{resolve:ssm:/demo-project/dev/private-subnet-1a}}'
        - '{{resolve:ssm:/demo-project/dev/private-subnet-1b}}'

  TaskDatabase:
    Type: AWS::RDS::DBInstance
    Properties: 
      DBName: taskdb
      DBInstanceIdentifier: task-rds-db
      Engine: postgres
      EngineVersion: '18.3'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      StorageType: gp3
      MasterUsername: task_admin
      MasterUserPassword: Admin#1234
      PubliclyAccessible: false
      VPCSecurityGroups:
        - '{{resolve:ssm:/demo-project/dev/rds-sg-id}}'
      DBSubnetGroupName: !Ref TaskRDSSubnetGroup
      MultiAZ: false
      BackupRetentionPeriod: 0
      DeletionProtection: false

  TaskConnectionStringSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo-project/dev/connection-string
      Type: String
      Value: !Sub 
        - 'Host=${Endpoint};Port=5432;Database=taskdb;Username=task_admin;Password=Admin#1234'
        - Endpoint: !GetAtt TaskDatabase.Endpoint.Address
    
  TaskRunMigrationSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /demo-project/dev/run-migration
      Type: String
      Value: "false"

Outputs:
  RDSEndpoint:
    Value: !GetAtt TaskDatabase.Endpoint.Address