AWSTemplateFormatVersion: 2010-09-09
Description: This is a cloudformation template for RDS database

Resources: 
  TaskRDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: demo-project/dev/rds-credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "task_admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  TaskRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This is a RDS subnet group for Private subnets
      SubnetIds:
        - !Sub '{{resolve:ssm:/demo-project/dev/private-subnet-1a}}'
        - !Sub '{{resolve:ssm:/demo-project/dev/private-subnet-1b}}'

  TaskDatabase:
    Type: AWS::RDS::DBInstance
    DependsOn: TaskRDSSecret
    Properties: 
      DBName: taskdb
      DBInstanceIdentifier: task-rds-db
      Engine: postgres
      EngineVersion: '18.3'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      StorageType: gp3
      MasterUsername: task_admin
      MasterUserPassword: !Sub '{{resolve:secretsmanager:demo-project/dev/rds-password:SecretString:password}}'
      PubliclyAccessible: false
      VPCSecurityGroup:
        - '{{resolve:ssm:/demo-project/dev/rds-sg-id}}'
      DBSubnetGroupName: !Ref TaskRDSSubnetGroup
      MultiAZ: false
      BackupRetentionPeriod: 0
      DeletionProtection: false

  TaskConnectionStringSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: demo-project/dev/connection-string
      Type: String
      Value: !Sub 
        - 'Host=${Endpoint};Port=5432;Database=taskdb;Username=task_admin;Password=${{resolve:secretsmanager:demo-project/dev/rds-password:SecretString:password}}'
        - Endpoint: !GetAtt TaskDatabase.Endpoint.Address

Outputs:
  RDSEndpoint:
    Value: !GetAtt TaskDatabase.Endpoint.Address