AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:  
    Type: String

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

Outputs:
  InternetGatewayId:
    Value: !Ref InternetGateway