AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GroupDescription:
    Type: String

  VpcId:  
    Type: String

  FromPort:
    Type: Number
    Default: 0

  IpProtocol:
    Type: String
    Default: ""

  ToPort:
    Type: Number
    Default: 0

  SourceSecurityGroupId:
    Type: String
    Default: ""

Conditions:
  HasIngressRule: !And
    - !Not [!Equals [!Ref SourceSecurityGroupId, ""]]
    - !Not [!Equals [!Ref IpProtocol, ""]]
    - !Not [!Equals [!Ref ToPort, 0]]
    - !Not [!Equals [!Ref FromPort, 0]]

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref GroupDescription
      VpcId: !Ref VpcId

  MySecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: HasIngressRule
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: !Ref IpProtocol
      FromPort: !Ref FromPort
      ToPort: !Ref ToPort
      SourceSecurityGroupId: !Ref SourceSecurityGroupId

Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup